// Event data parsed from schedule.txt
const events = [
  // Friday
  {
    day: 'friday',
    time: '6:00 PM',
    title: 'Dinner',
    location: 'main-dining',
    category: 'Food & Drink',
  },
  {
    day: 'friday',
    time: '7:30 PM',
    title: 'Comedy Night',
    location: 'main-dining',
    category: 'Entertainment',
  },
  {
    day: 'friday',
    time: '10:00 PM - midnight',
    title: 'Ecstatic Gong Rave',
    location: 'main-dining',
    category: 'Entertainment',
  },

  // Saturday
  {
    day: 'saturday',
    time: '7:30 AM',
    title: 'Breakfast',
    location: 'main-dining',
    category: 'Food & Drink',
  },
  {
    day: 'saturday',
    time: '8:15 AM',
    title: 'Vegan Runners',
    location: 'outside',
    category: 'Physical Activity',
    description:
      'Meeting in foyer at 8:15AM for lift share to Black Rocks, Wirksworth.',
  },
  {
    day: 'saturday',
    time: '9:00 AM',
    title: 'Vinyl Art Session 1',
    location: 'potting-shed',
    category: 'Arts & Crafts',
    description: 'Vinyl art with Frances session 1.',
  },
  {
    day: 'saturday',
    time: '9:00 AM',
    title: 'Laughter Therapy w/ Ishi',
    location: 'sports-hall',
    category: 'Physical Activity',
  },
  {
    day: 'saturday',
    time: '10:00 AM - 5:00 PM',
    title: 'Sauna & Ice Cold Shower',
    location: 'front-of-house',
    category: 'Holistic Therapies',
  },
  {
    day: 'all',
    time: 'All Weekend',
    title: 'Indian Head & Back Massage',
    location: 'bell-tent',
    category: 'Holistic Therapies',
    description:
      'Indian head and back massage, hot stones & facials with Wildflower Spirit – bell tent on front lawn.',
  },
  {
    day: 'all',
    time: 'All Weekend',
    title: 'Back & Head Massage',
    location: 'library',
    category: 'Holistic Therapies',
    description:
      'Back massage, Indian head massage, feet massage and gong bath with Living Balance – library.',
  },
  {
    day: 'all',
    time: 'All Weekend',
    title: 'Reflexology',
    location: 'conference-room',
    category: 'Holistic Therapies',
    description: 'Reflexology with Taylor – conference room.',
  },
  {
    day: 'all',
    time: 'All Weekend',
    title: 'Reiki & Crystal Healing',
    location: 'conference-room',
    category: 'Holistic Therapies',
    description:
      'Reiki and crystal healing with Jo and Niamh - conference room.',
  },
  {
    day: 'saturday',
    time: '10:00 AM',
    title: 'Vinyl Art Session 2',
    location: 'potting-shed',
    category: 'Arts & Crafts',
    description: 'Vinyl art with Frances session 2.',
  },
  {
    day: 'saturday',
    time: '10:15 AM',
    title: '5-a-side Football w/ Jen',
    location: 'sports-hall',
    category: 'Physical Activity',
  },
  {
    day: 'saturday',
    time: '10:00 AM',
    title: 'Rescue Not Retail Workshop w/ Illy Parrwood',
    location: 'small-dining',
    category: 'Education',
  },
  {
    day: 'saturday',
    time: '10:00 AM',
    title: 'Sushi Making Workshop',
    location: 'large-dining',
    category: 'Food & Drink',
  },
  {
    day: 'saturday',
    time: '11:00 AM',
    title: 'Fun Felt Creations w/ Brandy',
    location: 'potting-shed',
    category: 'Arts & Crafts',
  },
  {
    day: 'saturday',
    time: '11:00 AM',
    title: 'Building Local Groups',
    location: 'small-dining',
    category: 'Education',
    description:
      'Building local groups: the power of ground up organising with Tom Harris.',
  },
  {
    day: 'saturday',
    time: '12:00 PM',
    title: 'Candle Making w/ Mandy',
    location: 'potting-shed',
    category: 'Arts & Crafts',
  },
  {
    day: 'saturday',
    time: '12:00 PM',
    title: 'Yoga w/ Wild Yogi Wendy',
    location: 'sports-hall',
    category: 'Physical Activity',
    description: 'Yoga with Wild Yogi Wendy from FlowMotion Studios.',
  },
  {
    day: 'saturday',
    time: '12:00 PM',
    title: 'Animal Sanctuary Talk',
    location: 'small-dining',
    category: 'Education',
    description:
      'The highs and lows of running an animal sanctuary by Jac from Pigs in the Wood.',
  },
  {
    day: 'saturday',
    time: '12:00 PM',
    title: 'Sauerkraut Workshop w/ Lisa',
    location: 'large-dining',
    category: 'Food & Drink',
  },
  {
    day: 'saturday',
    time: '12:00 PM',
    title: 'Medicinal Forage w/ Rambling Rose Remedies',
    location: 'outside',
    category: 'Physical Activity',
    description: 'Medicinal forage and salve making. Meet in the foyer.',
  },
  {
    day: 'saturday',
    time: '1:00 PM',
    title: 'Lunch',
    location: 'main-dining',
    category: 'Food & Drink',
    description: 'Lunch served 1:00PM – 2:00PM.',
  },
  {
    day: 'saturday',
    time: '2:00 PM',
    title: 'Pottery',
    location: 'potting-shed',
    category: 'Arts & Crafts',
    description: 'Pottery workshop.',
  },
  {
    day: 'saturday',
    time: '2:00 PM',
    title: 'Charleston Dance w/ Becky Lamley',
    location: 'sports-hall',
    category: 'Dance',
  },
  {
    day: 'saturday',
    time: '2:00 PM',
    title: 'Return to the Old Ways',
    location: 'small-dining',
    category: 'Education',
    description: 'Return to the old ways – talk by John Awen.',
  },
  {
    day: 'saturday',
    time: '2:00 PM - 3:30 PM',
    title: 'Vegan Choir Practice',
    location: 'foyer',
    category: 'Music',
    description:
      'Vegan choir practise with Vegan Queen V and Sue from Little Green Pigeons.',
  },
  {
    day: 'saturday',
    time: '3:00 PM',
    title: 'Driftwood Art w/ Jo',
    location: 'potting-shed',
    category: 'Arts & Crafts',
  },
  {
    day: 'saturday',
    time: '3:00 PM',
    title: 'Keep Fit w/ Vegan Vikings',
    location: 'sports-hall',
    category: 'Physical Activity',
  },
  {
    day: 'saturday',
    time: '3:00 PM',
    title: 'Resilience and Burnout',
    location: 'small-dining',
    category: 'Education',
    description: 'Resilience and burnout by Dr Ishani Rao.',
  },
  {
    day: 'saturday',
    time: '3:00 PM',
    title: 'Forest Bathing w/ Poppy',
    location: 'outside',
    category: 'Physical Activity',
    description:
      'Forest bathing with Poppy from Wild and Wonder. Meet in the foyer.',
  },
  {
    day: 'saturday',
    time: '4:00 PM',
    title: 'Magic Mushrooms',
    location: 'potting-shed',
    category: 'Arts & Crafts',
    description: 'Magic mushrooms workshop.',
  },
  {
    day: 'saturday',
    time: '4:00 PM - 4:30 PM',
    title: 'Circus Skills w/ Jack & Amber',
    location: 'sports-hall',
    category: 'Physical Activity',
  },
  {
    day: 'saturday',
    time: '4:00 PM',
    title: 'Creative Poetry Writing w/ Sam',
    location: 'small-dining',
    category: 'Education',
  },
  {
    day: 'saturday',
    time: '4:30 PM',
    title: 'Swimming',
    location: 'outside',
    category: 'Physical Activity',
    description:
      'Swimming at New Bath Hotel and Spa (New Bath Road, DE4 3PX). Meet in the foyer at 4:30PM for lifts.',
  },
  {
    day: 'saturday',
    time: '5:00 PM',
    title: 'Belly Dancing w/ Nina',
    location: 'sports-hall',
    category: 'Dance',
  },
  {
    day: 'saturday',
    time: '5:00 PM',
    title: 'Communicate Veganism',
    location: 'small-dining',
    category: 'Education',
    description: 'How to communicate veganism effectively with Jordi.',
  },
  {
    day: 'saturday',
    time: '6:00 PM',
    title: 'Dinner',
    location: 'main-dining',
    category: 'Food & Drink',
  },
  {
    day: 'saturday',
    time: '7:00 PM - midnight',
    title: 'Live Music',
    location: 'foyer',
    category: 'Music',
    description: `Full schedule:
7:00 PM - Alan Jackson (Acoustic Folk)
7:50 PM - Owen Chambers (Intimate Piano & Vocals)
8:30 PM - Zoe + Bryce (Eclectic Covers)
9:20 PM - Dippy Bamba (Energetic Folk)
10:10 PM - Sweet Goose (Singer-songwriter folk)
11:00 PM - Vegan Queen V (The Legend Herself)`,
  },
  {
    day: 'saturday',
    time: '11:59 PM',
    title: 'After Party',
    location: 'main-dining',
    category: 'Music',
    description:
      'Kevin the DJ serving vegan vibes on the dance floor until 1:00 AM.',
  },
  {
    day: 'saturday',
    time: 'After Dark',
    title: 'Astronomy w/ Daniel',
    location: 'outside',
    category: 'Education',
    description: 'Astronomy session (if the sky is clear) – on the front lawn.',
  },

  // Sunday
  {
    day: 'sunday',
    time: '8:00 AM',
    title: 'Breakfast',
    location: 'main-dining',
    category: 'Food & Drink',
  },
  {
    day: 'sunday',
    time: '9:00 AM',
    title: 'Magic Mushroom Making Workshop',
    location: 'potting-shed',
    category: 'Arts & Crafts',
  },
  {
    day: 'sunday',
    time: '10:00 AM',
    title: 'Fun Felt Creations w/ Brandy',
    location: 'potting-shed',
    category: 'Arts & Crafts',
  },
  {
    day: 'sunday',
    time: '10:00 AM',
    title: 'Undermining Speciesism',
    location: 'small-dining',
    category: 'Education',
    description:
      'Undermining speciesism workshop with Allan and Immie Jackson of NARM.',
  },
  {
    day: 'sunday',
    time: '10:00 AM - 12:00 PM',
    title: 'Vegan Marketplace',
    location: 'sports-hall',
    category: 'Other',
    description: 'Vegan market place in the sports hall.',
  },
  {
    day: 'sunday',
    time: '11:00 AM',
    title: 'Candle Making w/ Mandy',
    location: 'potting-shed',
    category: 'Arts & Crafts',
  },
  {
    day: 'sunday',
    time: '11:00 AM',
    title: 'Diet and Nutrition w/ Vegan Vikings',
    location: 'small-dining',
    category: 'Education',
    description: 'Diet and nutrition with Alex and Tom from Vegan Vikings.',
  },
  {
    day: 'sunday',
    time: '11:00 AM',
    title: 'Meditation & Concert',
    location: 'foyer',
    category: 'Music',
    description: 'Meditation and gentle morning concert with Emaline Delapaix.',
  },
  {
    day: 'sunday',
    time: '12:00 PM',
    title: 'Active Hope Workshop',
    location: 'small-dining',
    category: 'Education',
    description: 'Active Hope workshop with Vegan counsellor Chrissy.',
  },
  {
    day: 'sunday',
    time: '1:00 PM',
    title: 'Lunch',
    location: 'main-dining',
    category: 'Food & Drink',
  },
  {
    day: 'sunday',
    time: '3:00 PM',
    title: 'Goodbyes & Departure',
    location: 'main-dining',
    category: 'Other',
    description:
      "Goodbyes and rooms cleared ready to leave by 3:00PM. For those who don't want the fun to end, Lumsdale Waterfall in Matlock is only a 10 minute drive away.",
  },

  // All weekend activities
  {
    day: 'all',
    time: 'All Weekend',
    title: 'Colouring & Games',
    location: 'main-dining',
    category: 'Arts & Crafts',
    description:
      'Colouring, leaf and pebble painting, board games and cards available during the whole weekend in the main dining room.',
  },
];
